# Generated by Django 4.2 on 2024-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='profile_images/'),
        ),
    ]
