# Generated by Django 4.2 on 2024-09-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0005_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
