# Generated by Django 4.2 on 2024-09-12 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0006_delete_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
