# Generated by Django 4.2 on 2024-09-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0008_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='pdf_url',
        ),
    ]
