# Generated by Django 4.2 on 2024-10-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0018_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='https://bucket-hernia.s3.amazonaws.com/images/usuario-logo2.png', upload_to='profile_images/'),
        ),
    ]
