# Generated by Django 4.2 on 2024-10-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0025_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/app/Hernia/static/images/usuario-logo2.png', upload_to='profile_images/usuario-logo3.png'),
        ),
    ]
