
# Generated by Django 4.2 on 2024-10-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0028_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='paciente_nombre',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]

