# Generated by Django 4.2 on 2025-11-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hernia', '0030_imagen_paciente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=500),
        ),
    ]
